Version = "1.0.0"

ApiListen = ":1314"

StartTime = "2018-08-01 00:00:00"

Debug = true

[redis]
Host = "localhost:6379"
MaxIdle = 3
MaxActive = 3
IdleTimeout = 240
ReadTimeout = 15
WriteTimeout = 15
ConnectTimeout = 15
